#!/usr/bin/php
<?php

function printwhy($mysqli, $sub, $super, $prefix = "") {
    $sql = "SELECT * FROM TraceData WHERE sub = '$sub' AND super = '$super'";
    $result = $mysqli->query($sql);
    $row = $result->fetch_assoc();

    //$res = $prefix . $row['sub'] . " -> " . $row['super'] . "    " . $row['type'] . "\n";
    echo $prefix . $row['sub'] . " -> " . $row['super'] . "    " . $row['type'] . "\n";
    
    $dependencies = json_decode($row['dependencies']);
    foreach ($dependencies as $dependency) {
        //$res .= printwhy($mysqli, $dependency->sub, $dependency->sup, $prefix . "    ");
        echo printwhy($mysqli, $dependency->sub, $dependency->sup, $prefix . "    ");
    }
    //return $res;
}

$mysqli = new mysqli("127.0.0.1", "root", "root", "ISGCI", 3306);
if ($mysqli->connect_errno) {
    echo "Failed to connect to MySQL: (" . $mysqli->connect_errno . ") " . $mysqli->connect_error;
    die;
}

echo printwhy($mysqli, 16, 3160, "");
