#!/usr/bin/python

""" Why does a certain ISGCI deduction hold?
Usage: why filename.trace gc_super gc_sub"""

import sys

def printwhy(fname, sup, sub, prefix):
   """Read in the trace file fname why sup is a superclass of sub and print
   this. Every output line is preceded by prefix."""

   pattern = sup +" -> "+ sub
   nodes = dict()
   f = open(fname)

   try:
      # Read the nodes
      while 1:
         line = f.readline()
         data = line.split('\t')        # This keeps the newline after the name
         if len(data) != 2:
            break
         nodes[data[0]] = data[1]

      # Find the inclusion
      while not line.startswith(pattern):
         line = f.readline()

      print prefix + pattern
      print prefix + nodes[sup],
      print prefix + "->"
      print prefix + nodes[sub],
      print prefix + line[len(pattern):].strip()
      sys.stdout.flush()
      line = f.readline()
      while line.startswith(" "):
         data = line.split()
         printwhy(fname, data[0], data[2], prefix+"   ")
         line = f.readline()

   finally:
      f.close()

printwhy(sys.argv[1], sys.argv[2], sys.argv[3], "")
